name: Deploy Pages
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install requirements
        run: pip install -r requirements-pages.txt
      - name: Generate synthetic data
        run: python scripts/generate_synthetic.py
      - name: Run baselines
        run: python scripts/run_baselines.py
      - name: Calibrate and evaluate
        run: python scripts/calibrate_and_eval.py
      - name: Make figures
        run: python scripts/make_figures.py
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
